[project]
name = "expenses"
description = "Gestion de dépenses partagées entre ami⋅es"
authors = [
    {name = "Rémi Côme", email ="remi.come@gmx.com"},
]
dynamic = ["version"]
dependencies = [
    "pydantic",
]

[project.optional-dependencies]
test = ["pytest"]
dev = ["ruff", "isort"]

[build-system]
requires = ["setuptools", "setuptools-scm[simple]"]
build-backend = "setuptools.build_meta"
